=== ts666823/tourist/SchemaXML/src/resource/note.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.WebServeSOA.net" xmlns="http://www.WebServeSOA.net"
           elementFormDefault="qualified">

    <xs:element name="resp">
        <xs:complexType >
            <xs:sequence>
                <xs:element name="city" type="xs:string" />
                <xs:element name="updatetime" type="xs:string" />
                <xs:element name="wendu" type="xs:string" />
                <xs:element name="fengli" type="xs:string" />
                <xs:element name="shidu" type="xs:string" />
                <xs:element name="fengxiang" type="xs:string" />
                <xs:element name="sunrise_1" type="xs:string" />
                <xs:element name="sunset_1" type="xs:string" />
                <xs:element name="sunrise_2" type="xs:string" />
                <xs:element name="sunset_2" type="xs:string" />
                <xs:element name="yesterday" >
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="date_1" type="xs:string" />
                            <xs:element name="high_1" type="xs:string" />
                            <xs:element name="low_1" type="xs:string" />
                            <xs:element name="day_1">
                                <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="type_1" type="xs:string" />
                                    <xs:element name="fx_1" type="xs:string" />
                                    <xs:element name="fl_1" type="xs:string" />
                                </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="night_1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="type_1" type="xs:string" />
                                        <xs:element name="fx_1" type="xs:string" />
                                        <xs:element name="fl_1" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="forecast" >
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="weather" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="date" type="xs:string" />
                                        <xs:element name="high" type="xs:string" />
                                        <xs:element name="low" type="xs:string" />
                                        <xs:element name="day" >
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="type" type="xs:string" />
                                                    <xs:element name="fengxiang" type="xs:string" />
                                                    <xs:element name="fengli" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="night" >
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="type" type="xs:string" />
                                                    <xs:element name="fengxiang" type="xs:string" />
                                                    <xs:element name="fengli" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="zhishus">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="zhishu" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string" />
                                        <xs:element name="value" type="xs:string" />
                                        <xs:element name="detail" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ts666823/tourist/SchemaXML/src/resource/note.xml
<?xml version="1.0"?>
<resp xmlns="http://www.WebServeSOA.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.WebServeSOA.net note.xsd">

    <city>北京</city>
    <updatetime>20:31</updatetime>
    <wendu>9</wendu>
    <fengli>
        <![CDATA[ 1级 ]]>
    </fengli>
    <shidu>75%</shidu>
    <fengxiang>东风</fengxiang>
    <sunrise_1>06:29</sunrise_1>
    <sunset_1>17:30</sunset_1>
    <sunrise_2/>
    <sunset_2/>
    <yesterday>
        <date_1>17日星期日</date_1>
        <high_1>高温 15℃</high_1>
        <low_1>低温 2℃</low_1>
        <day_1>
            <type_1>晴</type_1>
            <fx_1>西南风</fx_1>
            <fl_1>
                <![CDATA[ 2级 ]]>
            </fl_1>
        </day_1>
        <night_1>
            <type_1>晴</type_1>
            <fx_1>西南风</fx_1>
            <fl_1>
                <![CDATA[ 2级 ]]>
            </fl_1>
        </night_1>
    </yesterday>
    <forecast>
        <weather>
            <date>18日星期一</date>
            <high>高温 17℃</high>
            <low>低温 4℃</low>
            <day>
                <type>多云</type>
                <fengxiang>东北风</fengxiang>
                <fengli>
                    <![CDATA[ 2级 ]]>
                </fengli>
            </day>
            <night>
                <type>晴</type>
                <fengxiang>东北风</fengxiang>
                <fengli>
                    <![CDATA[ 2级 ]]>
                </fengli>
            </night>
        </weather>
        <weather>
            <date>19日星期二</date>
            <high>高温 13℃</high>
            <low>低温 1℃</low>
            <day>
                <type>多云</type>
                <fengxiang>东北风</fengxiang>
                <fengli>
                    <![CDATA[ 2级 ]]>
                </fengli>
            </day>
            <night>
                <type>多云</type>
                <fengxiang>东北风</fengxiang>
                <fengli>
                    <![CDATA[ 2级 ]]>
                </fengli>
            </night>
        </weather>
        <weather>
            <date>20日星期三</date>
            <high>高温 14℃</high>
            <low>低温 3℃</low>
            <day>
                <type>晴</type>
                <fengxiang>西南风</fengxiang>
                <fengli>
                    <![CDATA[ 1级 ]]>
                </fengli>
            </day>
            <night>
                <type>晴</type>
                <fengxiang>西南风</fengxiang>
                <fengli>
                    <![CDATA[ 1级 ]]>
                </fengli>
            </night>
        </weather>
        <weather>
            <date>21日星期四</date>
            <high>高温 17℃</high>
            <low>低温 4℃</low>
            <day>
                <type>晴</type>
                <fengxiang>西北风</fengxiang>
                <fengli>
                    <![CDATA[ 2级 ]]>
                </fengli>
            </day>
            <night>
                <type>晴</type>
                <fengxiang>西北风</fengxiang>
                <fengli>
                    <![CDATA[ 2级 ]]>
                </fengli>
            </night>
        </weather>
        <weather>
            <date>22日星期五</date>
            <high>高温 16℃</high>
            <low>低温 2℃</low>
            <day>
                <type>晴</type>
                <fengxiang>北风</fengxiang>
                <fengli>
                    <![CDATA[ 2级 ]]>
                </fengli>
            </day>
            <night>
                <type>晴</type>
                <fengxiang>北风</fengxiang>
                <fengli>
                    <![CDATA[ 2级 ]]>
                </fengli>
            </night>
        </weather>
    </forecast>
    <zhishus>
        <zhishu>
            <name>穿衣指数</name>
            <value>防寒春秋装</value>
            <detail>天气舒适，温度适宜。建议着风衣，毛衣，防寒服，大衣等，既舒适，又时尚。</detail>
        </zhishu>
        <zhishu>
            <name>紫外线强度</name>
            <value>紫外线最弱</value>
            <detail>紫外线较弱，对人体无太大影响，放心出门哦。</detail>
        </zhishu>
        <zhishu>
            <name>护肤指数</name>
            <value>常规护肤</value>
            <detail>空气适宜，请根据皮肤类型，选择适合的常规护肤品。</detail>
        </zhishu>
        <zhishu>
            <name>洗车指数</name>
            <value>很适宜洗车</value>
            <detail>天气晴朗，放心洗车吧，今明两天都暂无降水~</detail>
        </zhishu>
        <zhishu>
            <name>感冒指数</name>
            <value>易发感冒</value>
            <detail>感冒易发期，外出请适当调整衣物，注意补充水分。</detail>
        </zhishu>
        <zhishu>
            <name>晾晒指数</name>
            <value>较适宜晾晒</value>
            <detail>预计白天没有降水，温度适宜，较适合晾晒.</detail>
        </zhishu>
        <zhishu>
            <name>户外指数</name>
            <value>较适宜外出</value>
            <detail>天气还可以，预计白天没有降水，适合参加户外活动，适当锻炼身体。</detail>
        </zhishu>
        <zhishu>
            <name>污染指数</name>
            <value>轻微污染</value>
            <detail>空气质量良好，污染物浓度低，对健康人群无明显影响，可在户外适当活动。</detail>
        </zhishu>
        <zhishu>
            <name>钓鱼指数</name>
            <value>适宜</value>
            <detail>这样的天气非常适宜外出钓鱼，约个钓友出去钓鱼吧。</detail>
        </zhishu>
        <zhishu>
            <name>中暑指数</name>
            <value>不易中暑</value>
            <detail>预计今日整体天气适中，中暑的可能性较低，无需做特殊防护。</detail>
        </zhishu>
        <zhishu>
            <name>舒适度</name>
            <value>不舒适</value>
            <detail>天气很冷，大部分人会感到不舒适。</detail>
        </zhishu>
        <zhishu>
            <name>赏月指数</name>
            <value>不适宜赏月</value>
            <detail>今晚看不到月亮，不适合赏月</detail>
        </zhishu>
    </zhishus>
</resp>
